<?php
/**
 * Product description template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>

<?php
$product = $block->getProduct();
?>
<div class="detail-inner" <?php if ($block->getProduct()->getData('detail_product') != null){echo "style='display: block';";}else{echo "style='display: none';";} ?>>
    <div class="detail-content">
        <?= /* @noEscape */ $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
            $block->getProduct(),
            $block->getProduct()->getData('detail_product'),
            'Detail Product'
        ) ?>
    </div>

    <div class="our-mission">
        <div class="our-mission-text-container">
            <?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('our-mission-container')->toHtml();?>
        </div>
    </div>
</div>


