
<div class="container">
    <a data-fancybox data-src="#modal" href="javascript:;" class="btn btn-primary size-chart-btn">Size Chart</a>
    <div style="display: none;" id="modal">
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('size-chart')->toHtml();?>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".size-chart-btn": {
            "mainjs": {"size_chart": "size-chart"}
        },
        ".tab-wrapper": {
            "mainjs": {"size_chart_tab": "size-chart-tab"}
        }
    }
</script>


