<div id="accordion__inner">
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 1</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores culpa deserunt doloribus molestias sapiente sint ut. Asperiores ea earum eveniet fugit, illum incidunt libero mollitia nam, nihil quaerat qui, unde.
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 2</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, atque aut blanditiis cupiditate debitis eos esse est excepturi illum magnam molestias nihil odit quae quo quos repellendus, reprehenderit sunt ut?
    </div>
rev
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 3</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid cum dolor eveniet ex excepturi impedit ipsam non velit? Beatae est explicabo harum magni qui rem repudiandae. Odio, quisquam, voluptatibus.
    </div>
</div>

<div id="accordion__inner-second" data-mage-init='{
        "accordion":{
            "active": [1, 2],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 1</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores culpa deserunt doloribus molestias sapiente sint ut. Asperiores ea earum eveniet fugit, illum incidunt libero mollitia nam, nihil quaerat qui, unde.
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 2</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, atque aut blanditiis cupiditate debitis eos esse est excepturi illum magnam molestias nihil odit quae quo quos repellendus, reprehenderit sunt ut?
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <span>Title 3</span>
        </div>
    </div>
    <div data-role="content">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad aliquid cum dolor eveniet ex excepturi impedit ipsam non velit? Beatae est explicabo harum magni qui rem repudiandae. Odio, quisquam, voluptatibus.
    </div>
</div>

<script type="text/x-magento-init">
    {
        "#accordion__inner": {
            "mainjs": {"wrapper_accordion": "accordion"}
        }
    }
</script>
