<div class="container">
    <div class="banner-exclusive__inner">
        <div class="banner-exclusive__text">
            <div class="banner-exclusive__heading">Exclusive to<br>The Irish Store</div>
            <div class="banner-exclusive__sub">Find a little piece of Ireland you can’t get anywhere else.</div>
            <a class="banner-exclusive__button" href="https://www.theirishstore.com/exclusive">SHOP NOW</a>
        </div>
    </div>
</div>

