<div class="banner-discount__inner">
    <div class="banner-discount__content">
        <div class="banner-discount__content-head">GET 20% OFF</div>
        <div class="banner-discount__content-title">For each friend you refer</div>
        <div class="banner-discount__content-text">And we'll give them each<strong> 20% off</strong> when they place
            their first order too.
        </div>
        <div class="banner-discount__content-btn"><a href="https://www.theirishstore.com/refer-a-friend">GET OFFER</a>
        </div>
    </div>
</div>
