<div class="container">
    <div class="categories__inner">
        <div class="categories__item"><img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/categories1.jpg">
            <a class="categories__item-content" href="https://www.theirishstore.com/men">
                <button class="overlay" style="background: rgba(0,0,0,0.5);" title="Irish Knitwear Clothing">
                    Shop Women
                </button>
            </a></div>
        <div class="categories__item"><img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/categories2.jpg">
            <a class="categories__item-content" href="https://www.theirishstore.com/men">
                <button class="overlay" style="background: rgba(0,0,0,0.5);" title="Irish Gifts">
                    Shop Irish Gifts
                </button>
            </a></div>
        <div class="categories__item">
            <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/categories3.jpg">
            <a class="categories__item-content" href="https://www.theirishstore.com/men">
                <button class="overlay" style="background: rgba(0,0,0,0.5);" title="Shop Sale">Shop Men</button>
            </a>
        </div>
    </div>
</div>

