<div class="company__inner">
    <div class="company__title">
        The Irish Store as mentioned in:
    </div>
    <div class="company__content">
        <a href="#">
            <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/theirishtimes.webp">
        </a>
        <a href="#">
            <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/thenewyorker.png">
        </a>
        <a href="#">
            <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/thenewyorktimes.png">
        </a>
    </div>
</div>

