<div class="company__inner">
    <div class="company__title">
        The Irish Store as mentioned in:
    </div>
    <div class="company__content">
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/theirishtimes.webp'); ?>" />
        </a>
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/thenewyorker.png'); ?>" />
        </a>
        <a href="#">
            <img src="<?php echo $block->getViewFileUrl('images/thenewyorktimes.png'); ?>" />
        </a>
    </div>
</div>

