<div class="products-slider__inner">
    <div class="test-slick">
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product2.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> Connemara Marble Disc Earrings &amp; Pendant Jewelry
                    Set </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">$72.76</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product3.png">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Cape Clear Aran Dress - NEW </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $100.07</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product4.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Lough Dan Aran Cardigan - NEW </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $109.17</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product5.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product5.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product5.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="products-slider__item item">
            <div class="products-slider__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/product5.jpg">
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".test-slick": {
            "testjs": {"wrapper_slick": "products-slider__inner"}
        }
    }
</script>
