<div class="container">
    <div class="features-second__inner">
        <div class="features-second__item">
            <div class="features-second__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/features2.jpg">
            </div>
            <div class="features-second__item-content">
                <h3>Celtic Jewelry</h3>
                <a title="Irish Gifts" href="https://www.theirishstore.com/celtic-jewelry">
                    <button class="white">Shop Jewelry</button>
                </a>
            </div>
        </div>
        <div class="features-second__item">
            <div class="features-second__item-images">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/features3.jpg">
            </div>
            <div class="features-second__item-content">
                <h3>Homeware Gifts</h3>
                <a title="Irish Knitwear" href="https://www.theirishstore.com/irish-gifts-for-the-home">
                    <button class="white">Shop Homeware Gifts</button>
                </a>
            </div>
        </div>
    </div>
</div>

