<div class="hero__inner content">
    <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/ourbiggestsale.webp">
    <hr class="hrfistline">
    <div class="cybermondaytxt">CLEARANCE SALE</div>
    <hr class="hrsecondline">
    <div class="cybermondaytxtupto">up to</div>
    <div class="cmondaypercentofftxt">75% OFF</div>
    <div class="_2freegiftsovertxt">Selected sizes &amp; colors | While stocks last</div>
    <div class="hero-link">
        <span class="widget block block-category-link-inline">
            <a href="https://magento2.test/women.html"><span>SHOP NOW</span></a>
        </span>
    </div>
</div>

