<div class="journey__inner">
    <div class="journey__content">
        <div class="journey__content-logo">
            <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/tis-logo.svg">
        </div>
        <div class="journey__content-banner">
            The Irish Store Journey.
        </div>
        <div class="journey__content-link">
            <a title="Our Story" href="https://www.theirishstore.com/our-story">
                <button class="overlay" style="background-color: white; color: black;">See our journey</button>
            </a>
        </div>
    </div>
</div>

