<button type="button" class="action" data-trigger="trigger">
    <span>Click</span>
</button>
<div data-mage-init='{ "Magento_Ui/js/modal/modal": {
            "type": "popup",
            "title": "Popup title",
            "trigger": "[data-trigger=trigger]",
            "responsive": true,
            "buttons": [{
                "text": "Submit",
                "class": "action"
            }]
        }}'>
    <div class="content">
        Popup Content
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad dolorum hic laborum nesciunt saepe sapiente sequi. Aliquam, aut doloribus, earum esse hic in inventore nam perferendis, quibusdam repellat sequi sint.
    </div>
</div>


<div class="modal-second">
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. A cupiditate eveniet incidunt non odit porro possimus quasi repellendus! A autem consequuntur ea eos harum nam odit porro quia! Illum, pariatur.
</div>
<p class="click-second">vxvvxvxv</p>

<script type="text/x-magento-init">
    {
        ".click-second": {
            "mainjs": {"content": ".modal-second"}
        }
    }
</script>
