<div class="products-slider__title">
    <span>OUR TOP PICKS</span>
</div>
<div class="swiper-container products-slider__inner" data-mage-init='{"mainjs": {}}'>
    <div class="swiper-wrapper ">
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product1.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> Hooded Aran Zipper Coat </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $149.95</div>
                    <div class="products-slider__item-price_now">Now $99.95</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product2.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> Connemara Marble Disc Earrings &amp; Pendant Jewelry
                    Set </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">$72.76</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product3.png'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Cape Clear Aran Dress - NEW </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $100.07</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product4.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Lough Dan Aran Cardigan - NEW </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $109.17</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product5.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product1.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
        <div class="swiper-slide products-slider__item">
            <div class="products-slider__item-images">
                <img src="<?php echo $block->getViewFileUrl('images/product2.jpg'); ?>" />
            </div>
            <div class="products-slider__item-content">
                <a class="products-slider__item-title" href="#"> The Valentia Aran Cardigan </a>
                <div class="products-slider__item-price">
                    <div class="products-slider__item-price_was">Was $118.27</div>
                    <div class="products-slider__item-price_now">Now $90.97</div>
                </div>
            </div>
        </div>
    </div>
    <div class="swiper-pagination products-slider__pagination"></div>
</div>



