<div class="product data items second-tab">
    <div class="item title second-tab-item" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-cinema">Cinema</a>
    </div>
    <div id="tab-cinema" class="item content" data-role="content">Cinema content</div>

    <div class="item title second-tab-item" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-Motorcycle">Motorcycle</a>
    </div>
    <div id="tab-Motorcycle" class="item content" data-role="content">Motorcycle content</div>

    <div class="item title second-tab-item" data-role="collapsible">
        <a class="switch" data-toggle="trigger" href="#tab-book">Book</a>
    </div>
    <div id="tab-book" class="item content" data-role="content">Book Content</div>
</div>


<script type="text/x-magento-init">
    {
        ".tab": {
            "mainjs": {"wrapper_tab": "second-tab"}
        }
    }
</script>
