<div class="test" style="display: none">
    <?php echo('test text'); ?>
    <?= __('eng') ?>
    <?php $block->getChildHtml() ?>
<!--    // getChildHtml приймає alias-->
    <?php $block->getBlockHtml('') ?>
<!--    використовується якщо в блоці потрібно відрендерити інший блок, передається name-->
    <?php $block->getTestData() ?>
<!--    однакове з getData ('')-->
    <?php $block->getData('test_data') ?>
</div>


