<div class="tis__inner">
    <ul class="tis-list">
        <li class=" shipping">
            <div class="shipping-icon">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/tis-icon4.svg" alt="shipping icon">
            </div>
            <div class="tis-link">
                <a href="#" target="_self"><strong>Free Returns</strong><br>up to 6 months</a>
            </div>
        </li>
        <li class="tax-free">
            <div class="shopping-icon">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/tis-icon3.svg" alt="shipping icon">
            </div>
            <div class="tis-link">
                <a href="#" target="_self"><strong>FAST SHIPPING</strong><br>Ireland to USA</a>
            </div>
        </li>
        <li class="feefo">
            <div class="review-icon"><img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/tis-icon1.svg" alt="review icon"></div>
            <div class="feefo-content">
                <strong>
                    <a href="#" target="_blank" rel="noopener"><img class="feefo-logo" src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/feefo.webp" alt="FeefoLogo" width="55px" height="13px">Gold</a>
                </strong><br>
                98% customer satisfaction
            </div>
        </li>
        <li class="tax-free">
            <div class="shopping-icon">
                <img src="https://magento2.test/static/frontend/MyTheme/air/en_US/images/tis-icon2.webp">
            </div>
            <div class="tis-link">
                <a href="#" target="_self">
                    <strong>100% IRISH OWNED</strong><br>
                    30 years experience
                </a>
            </div>
        </li>
    </ul>
</div>
