<div class="container">
    <div class="video-presentation__inner">
        <div class="video-presentation__item">
            <div class="video">
                <a data-fancybox href="https://www.youtube.com/embed/rMtA10i-yIU">
<!--                    <img class="card-img-top img-fluid" src="https://i.ytimg.com/vi/rMtA10i-yIU/hqdefault.jpg" />-->
                    <img class="card-img-top img-fluid" src="<?php echo $block->getViewFileUrl('images/hqdefault.jpg'); ?>" />
                    <div class="play"></div>
                </a>
            </div>
            <div class="video-presentation__item-title">Traditional Irish Aran Sweaters</div>
            <div class="video-presentation__item-text">The finest Irish clothing, homeware and gifts. Perfect to enjoy
                yourself or give to friends and loved ones.
            </div>
            <div class="video-presentation__item-link">
                <a class="video-presentation__button-links" href="https://www.theirishstore.com/aran-sweaters">SHOP
                    NOW</a>
            </div>
        </div>
        <div class="video-presentation__item">
            <div class="video">
                <a data-fancybox href="https://www.youtube.com/embed/BBBfVZsqhrw">
<!--                    <img class="card-img-top img-fluid" src="https://i.ytimg.com/vi/BBBfVZsqhrw/hqdefault.jpg" />-->
                    <img class="card-img-top img-fluid" src="<?php echo $block->getViewFileUrl('images/hqdefault2.jpg'); ?>" />
                    <div class="play"></div>
                </a>
            </div>
            <div class="video-presentation__item-title">Traditional Irish Aran Sweaters</div>
            <div class="video-presentation__item-text">The finest Irish clothing, homeware and gifts. Perfect to enjoy
                yourself or give to friends and loved ones.
            </div>
            <div class="video-presentation__item-link">
                <a class="video-presentation__button-links" href="https://www.theirishstore.com/aran-sweaters">SHOP
                    NOW</a>
            </div>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        ".video a": {
            "mainjs": {"wrapper_fancybox": "video-presentation__item"}
        }
    }
</script>

